sudo: false
language: python
python:
  - "2.7"
install:
  - pip install python-coveralls
  - pip install tox-travis
  - pip install lambda-uploader
script: tox
after_success:
  - ls -la
  - find ./ -name .coverage
  - coveralls --data_file tests/.coverage
  - pip install .
  - Lambda-uploader
