sudo: false
language: python
python:
  - "2.7"
install:
  - pip install tox-travis
  - pip install lambda-uploader
  - ./set_creds.sh
script: tox
after_success:
  - pip install -r requirements.txt -t .
  - lambda-uploader
