echo "[Amazon]
AMAZON_ACCESS_KEY = $ROOT_AMAZON_ACCESS_KEY
AMAZON_SECRET_KEY = $ROOT_AMAZON_SECRET_KEY
AMAZON_ASSOC_TAG = $ROOT_AMAZON_ASSOC_ID

[Google]
GOOGLE_DEVELOPER_KEY = $GOOGLE_DEVELOPER_KEY
GOOGLE_CUSTOM_SEARCH_ENGINE_KEY = $GOOGLE_CUSTOM_SEARCH_ENGINE_KEY " > credentials.ini